// *****************************************************************************
// Copyright (C) 2026 Theia contributors and Qaap product fork.
// SPDX-License-Identifier: EPL-2.0 OR GPL-2.0-only WITH Classpath-exception-2.0
// *****************************************************************************

// The shared contract between `MobileOneColumnShellContribution` and the extracted free functions in the
// `mobile-one-column-shell-contribution-*.ts` cluster. Each extracted function receives the host typed as
// `MobileOneColumnShellContributionContext` instead of `any`. The contract is picked from the class over an explicit member
// list, so every member keeps the exact type the class declares. Members named here are `public`
// (+ `@internal` where they used to be `protected`) on the class.
// `import type` keeps this free of a runtime import cycle (the class imports every extracted module).

import type { MobileOneColumnShellContribution } from './mobile-one-column-shell-contribution';

/** Members referenced by the extracted `mobile-one-column-shell-contribution-*` modules. */
export type MobileOneColumnShellContributionContextMember =
    | 'activateMainPreviewWidget'
    | 'activateMobileIdeHeaderView'
    | 'activeTasks'
    | 'agUiFrontendTools'
    | 'agentFinishedToast'
    | 'agentTaskComposer'
    | 'appearanceModeService'
    | 'armAgentsSurfaceWatchdog'
    | 'armBootGuardSafetyTimeout'
    | 'backgroundContext'
    | 'bootstrapMobilePreviewInBackground'
    | 'bottomBarController'
    | 'bottomBarHost'
    | 'chatAgentService'
    | 'chatService'
    | 'clipboardService'
    | 'closeStaleMainPreviewWidget'
    | 'collapseMobileSidePanels'
    | 'collapseMobileSideSheets'
    | 'colorRegistry'
    | 'commands'
    | 'commitMessageAi'
    | 'composerEditorContextService'
    | 'composerPromptImprover'
    | 'composerPromptService'
    | 'conversationFlags'
    | 'conversations'
    | 'createProjectsPanel'
    | 'decorationsService'
    | 'desktopTerminalLayout'
    | 'dismissSheetsAsync'
    | 'editorManager'
    | 'elementInspectorService'
    | 'enforceWorkHubSurfaceIsolation'
    | 'ensureDesktopSidePanelSizes'
    | 'ensureDesktopWorkHubSessionsSidebarOpen'
    | 'ensureMainContentAfterWorkspaceReload'
    | 'ensureMobilePreviewEditorVisible'
    | 'ensureMobileProjectsHomeVisible'
    | 'ensureOverlayElements'
    | 'ensureProjectsPanel'
    | 'ensureShellHooks'
    | 'ensureWelcomeInMainArea'
    | 'enterMobileLayout'
    | 'executeAndDismiss'
    | 'fileService'
    | 'fileUploadService'
    | 'findPreviewWidget'
    | 'forceCenterColumnFullWidth'
    | 'frontendStateService'
    | 'getActivePreviewWidget'
    | 'getMainPreviewWidget'
    | 'hasLayoutRecoveryBeenAttempted'
    | 'hideProjectsPanel'
    | 'hidePullRequestPanel'
    | 'hubNavigation'
    | 'hubNavigationHost'
    | 'ideFallback'
    | 'ideFallbackHost'
    | 'inboxStream'
    | 'initBottomBarController'
    | 'initHubNavigationController'
    | 'initIdeFallbackController'
    | 'initOverlayController'
    | 'initProjectsPanelFactory'
    | 'initPullRequestPanelController'
    | 'initSideSheetController'
    | 'initTranscriptChromeController'
    | 'initWorkHubBootstrapController'
    | 'isMainPreviewWidgetLive'
    | 'isMobileAgentSheetVisible'
    | 'isMobileExploreSheetVisible'
    | 'isProjectsLandingSession'
    | 'isWorkHubSurfacePresentInDom'
    | 'labelProvider'
    | 'landing'
    | 'landingHost'
    | 'landingLeftThisSession'
    | 'languageModelRegistry'
    | 'leaveMobileLayout'
    | 'markLayoutRecoveryAttempted'
    | 'markdownPreviewHandler'
    | 'mcpFrontendService'
    | 'messageService'
    | 'miniBrowserOpenHandler'
    | 'mobileActive'
    | 'mobileMq'
    | 'mobileProjectChatViewWidgetFactory'
    | 'monacoEditorProvider'
    | 'mountSideSheetWidget'
    | 'onCurrentProjectActivated'
    | 'onDismissProjectsPanelEvent'
    | 'onFrontendReadyEnsureWorkHub'
    | 'onLandingHubListChanged'
    | 'onMediaChange'
    | 'onProjectsPanelOpen'
    | 'onProjectsPanelOpenInIde'
    | 'onProjectsWorkspaceOpened'
    | 'onWindowResize'
    | 'openAgentTaskComposer'
    | 'openConversationInWorkHub'
    | 'openDesktopIde'
    | 'openMobilePreviewInMain'
    | 'openMobileSideSheet'
    | 'openMobileWorkHubLanding'
    | 'openPullRequestFromInbox'
    | 'openWorkHubAiConfigurationSheet'
    | 'openWorkHubBillingSheet'
    | 'openWorkHubPreferencesSheet'
    | 'overlayController'
    | 'overlayHost'
    | 'patchWorkHubBootstrapLandingHost'
    | 'persistWorkHubSurfacePreference'
    | 'preferenceService'
    | 'prepareDesktopIdeWorkspaceFromHub'
    | 'prepareSideSheetOpen'
    | 'previewSurfaceRegistry'
    | 'projectBootstrap'
    | 'projectsCount'
    | 'projectsPanel'
    | 'projectsPanelFactory'
    | 'projectsPanelTrack'
    | 'projectsReadme'
    | 'projectsService'
    | 'promptService'
    | 'pullRequestPanelController'
    | 'pullRequestPanelHost'
    | 'quickInputService'
    | 'recoverEmptyAgentsSurface'
    | 'refreshBottomBar'
    | 'refreshProjectsCount'
    | 'refreshWorkbenchTopBar'
    | 'relayoutMainPreviewWidgets'
    | 'relocatePreviewToMainIfNeeded'
    | 'requestFullShellRelayout'
    | 'resizeRaf'
    | 'resolveCurrentProjectForAgent'
    | 'resolveMobileIdeHeaderViewId'
    | 'restoreDesktopSplitLayout'
    | 'restoreMobileBottomPanelFromMaximized'
    | 'returnToAgentsFromDesktopIde'
    | 'runLayoutRecoveryGuard'
    | 'scheduleSnapAndUiRefresh'
    | 'scmService'
    | 'sessionState'
    | 'setSidePanelSize'
    | 'setTrackedProjectsPanel'
    | 'settleMobileSidePanelsCollapsed'
    | 'shell'
    | 'shouldActivateMobileLayout'
    | 'shouldActivateWorkHubLayout'
    | 'shouldDismissSheetsForButton'
    | 'showMobileProjectsHome'
    | 'sideSheetController'
    | 'sideSheetHost'
    | 'skillService'
    | 'statusBar'
    | 'storageService'
    | 'syncIdeMiniBrowserPreviewSuspension'
    | 'syncMobileHubPrimaryBottomChrome'
    | 'syncOverlayEdgeSwipeZones'
    | 'teardownMobileUi'
    | 'terminalService'
    | 'themeService'
    | 'toDispose'
    | 'toggleMobileAgentSheet'
    | 'toggleMobileExploreSheet'
    | 'toggleMobilePreview'
    | 'toggleProjectsPanel'
    | 'toggleWorkHubSessionsSidebar'
    | 'transcriptChrome'
    | 'transcriptChromeHost'
    | 'tryBootstrapMobileAgentsChat'
    | 'variableService'
    | 'widgetManager'
    | 'workHubBillingSheet'
    | 'workHubBootstrap'
    | 'workHubBootstrapHost'
    | 'workHubDiff'
    | 'workHubPreferencesSheet'
    | 'workHubProjectSkillRoots'
    | 'workspaceService';

/**
 * Members of {@link MobileOneColumnShellContribution} that the extracted helper functions
 * access through their `ctx` parameter.
 */
export interface MobileOneColumnShellContributionContext
    extends Pick<MobileOneColumnShellContribution, MobileOneColumnShellContributionContextMember> { }
