// *****************************************************************************
// Copyright (C) 2026 Theia contributors and Qaap product fork.
// SPDX-License-Identifier: EPL-2.0 OR GPL-2.0-only WITH Classpath-exception-2.0
// *****************************************************************************

// The shared contract between `QaapProjectBootstrapService` and the extracted free functions in the
// `qaap-project-bootstrap-service-*.ts` cluster. Each extracted function receives the host typed as
// `QaapProjectBootstrapServiceContext` instead of `any`. The contract is picked from the class over an explicit member
// list, so every member keeps the exact type the class declares. Members named here are `public`
// (+ `@internal` where they used to be `protected`) on the class.
// `import type` keeps this free of a runtime import cycle (the class imports every extracted module).

import type { QaapProjectBootstrapService } from './qaap-project-bootstrap-service';

/** Members referenced by the extracted `qaap-project-bootstrap-service-*` modules. */
export type QaapProjectBootstrapServiceContextMember =
    | '_descriptor'
    | '_error'
    | '_forwardedPorts'
    | '_lastPort'
    | '_missingDescriptorHint'
    | '_needsInstall'
    | '_phase'
    | '_portConflictDetected'
    | '_portConflictPort'
    | '_previewReadiness'
    | '_previewUrl'
    | '_previewWaitTimedOut'
    | '_selectedApp'
    | 'activeDevPortHint'
    | 'activePreviewClaim'
    | 'activePreviewConversationId'
    | 'activePreviewRunId'
    | 'activeProjectId'
    | 'activeWorkspaceRoot'
    | 'adoptExistingPreviewIdentity'
    | 'adoptSupersedingPreviewClaim'
    | 'appendDevOutput'
    | 'attachTerminalOsProcessId'
    | 'attemptedDevPorts'
    | 'automaticPortRecoveryAttempts'
    | 'beginDevRun'
    | 'bindPreviewConversation'
    | 'buildDevSpawnPlan'
    | 'buildShellInvocation'
    | 'buildStateChange'
    | 'cancelDevPreviewFallbacks'
    | 'cancelDevPreviewHealthMonitor'
    | 'cancelDevPreviewWarmup'
    | 'claimDevPreviewPort'
    | 'cleanupDevTerminal'
    | 'clearForwardedPorts'
    | 'collectProbePorts'
    | 'delay'
    | 'detector'
    | 'devOutputTail'
    | 'devPortOverride'
    | 'devPreviewFallbackTimers'
    | 'devPreviewHealthFailures'
    | 'devPreviewHealthTimer'
    | 'devPreviewWarmupTimer'
    | 'devRunCancelledByUser'
    | 'devRunGeneration'
    | 'devTerminal'
    | 'devTerminalByConversationId'
    | 'devTerminalConversationId'
    | 'devTerminalListener'
    | 'disposeBootstrapTerminal'
    | 'disposeRestoredPreviewTerminals'
    | 'enrichDevRunError'
    | 'ensurePreviewProcessIdForConversation'
    | 'extractPort'
    | 'extractPortFromInUseMessage'
    | 'failDevRun'
    | 'forwardedPorts'
    | 'forwardedPortsEmitter'
    | 'getMissingDescriptorHint'
    | 'healPreviewClaimToListeningPort'
    | 'hubPinnedWorkspaceRoot'
    | 'hubProjects'
    | 'installGeneration'
    | 'installTerminal'
    | 'markPortOpened'
    | 'mayAutoOpenPreviewNow'
    | 'miniBrowser'
    | 'monitorPreviewProcessLifetime'
    | 'monorepoAppSwitchGeneration'
    | 'monorepoAppSwitchPromise'
    | 'normalizeDevUrl'
    | 'openPreview'
    | 'openPreviewWidget'
    | 'openPrimaryPreviewWhenReady'
    | 'pendingMonorepoAppPath'
    | 'persistPhase'
    | 'portRecoveryFrom'
    | 'previewAutoOpenGate'
    | 'previewAutoRetryAttempts'
    | 'previewAutoRetryTimer'
    | 'previewClaimByConversation'
    | 'previewPortClaimService'
    | 'previewProjectId'
    | 'previewRunIdByConversation'
    | 'previewWidgetKey'
    | 'probeBelongsToActiveProject'
    | 'readAllPersisted'
    | 'readPersisted'
    | 'readTerminalTail'
    | 'reconcileRestoredPreviewTerminals'
    | 'reconcileSupersededPreviewClaim'
    | 'recordForwardedPort'
    | 'refreshDebounceTimer'
    | 'refreshDescriptorAfterInstall'
    | 'refreshFromCurrentWorkspace'
    | 'refreshFromRoot'
    | 'registerDevTerminalForConversation'
    | 'releaseActivePreview'
    | 'releaseDevTerminalForConversation'
    | 'rememberActivePreviewClaim'
    | 'reserveActivePreview'
    | 'resetBootstrapSessionForWorkspace'
    | 'resolveDevPlan'
    | 'resolveInstallPlan'
    | 'resolvePrimaryPreviewTarget'
    | 'runDevServer'
    | 'runInstall'
    | 'scanDevOutput'
    | 'scanForDevUrl'
    | 'scheduleDevPreviewFallback'
    | 'scheduleDevPreviewWarmup'
    | 'scheduleRefreshFromCurrentWorkspace'
    | 'setPhase'
    | 'shell'
    | 'spawnCommand'
    | 'spawnCommandWithRetry'
    | 'startDevPreviewHealthMonitor'
    | 'startDevServer'
    | 'stateEmitter'
    | 'stopManagedDevServerForAppSwitch'
    | 'switchMonorepoApp'
    | 'syncHubSession'
    | 'syncMiniBrowserPreviewSuspensionAfterOpen'
    | 'terminalService'
    | 'terminalWatcher'
    | 'toDispose'
    | 'toUserFacingDevError'
    | 'tryAttachToExistingServer'
    | 'waitForExit'
    | 'warmupDevPreview'
    | 'watchAttachedDevTerminal'
    | 'workspaceService';

/**
 * Members of {@link QaapProjectBootstrapService} that the extracted helper functions
 * access through their `ctx` parameter.
 */
export interface QaapProjectBootstrapServiceContext
    extends Pick<QaapProjectBootstrapService, QaapProjectBootstrapServiceContextMember> { }
