// *****************************************************************************
// Copyright (C) 2026 Theia contributors and Qaap product fork.
// SPDX-License-Identifier: EPL-2.0 OR GPL-2.0-only WITH Classpath-exception-2.0
// *****************************************************************************

// The shared contract between `MobileProjectsTranscriptSurfacesUi` and the extracted free functions
// in the `mobile-projects-transcript-surfaces-ui-*.ts` cluster. Each extracted function receives the
// UI typed as `MobileProjectsTranscriptSurfacesUiContext` instead of `any`. As with
// `MobileProjectsTranscriptMessagesArtifactsUiContext`, the contract is picked from the class over an
// explicit member list, so every member keeps the exact type the class declares. Members named here
// are `public` (+ `@internal` where they used to be `protected`) on the class. `import type` keeps
// this free of a runtime import cycle (the class imports every extracted module).

import type { MobileProjectsTranscriptSurfacesUi } from './mobile-projects-transcript-surfaces-ui';

/** Members referenced by the extracted `mobile-projects-transcript-surfaces-ui-*` modules. */
export type MobileProjectsTranscriptSurfacesUiContextMember =
    | 'adoptReadyTranscriptPreview'
    | 'adoptReconciledProjectPreviewUrl'
    | 'annotateEmptyPreviewWhenNotRunnable'
    | 'applyTranscriptPreviewRunButtonState'
    | 'beginTranscriptDevPreviewRequest'
    | 'bootstrapAppliesToProject'
    | 'bootstrapPreviewUrlForProject'
    | 'bootstrapRunningPreviewUrl'
    | 'cancelPreviewAgentTurn'
    | 'claimTranscriptPreviewExecution'
    | 'clearMismatchedProjectPreviewUrl'
    | 'clearPreviewRuntimeForConversation'
    | 'clearTranscriptEmptyPreviewChrome'
    | 'closeTranscriptPreviewAppPicker'
    | 'closeTranscriptTerminalTab'
    | 'createTranscriptPreviewRunButton'
    | 'createTranscriptTerminalSlide'
    | 'detachTranscriptFilesFromHost'
    | 'detachTranscriptReviewWidget'
    | 'detachTranscriptTerminalFromHost'
    | 'discoverAndMountTranscriptPreviewIfReady'
    | 'discoverProjectDevPreviewUrl'
    | 'disposeTranscriptEmbeddedPreview'
    | 'disposeTranscriptTerminalSlides'
    | 'embeddedPreviewByConversationScopeId'
    | 'ensurePreviewProjectContext'
    | 'ensureTranscriptFilesTab'
    | 'ensureTranscriptPreviewServing'
    | 'ensureTranscriptTerminalChrome'
    | 'ensureTranscriptTerminalTab'
    | 'executionFilesHost'
    | 'executionPreviewHost'
    | 'executionSurfaceHost'
    | 'executionTerminalHost'
    | 'fetchCurrentProjectClaimUrl'
    | 'getOrCreateOffscreenPreviewHost'
    | 'getTranscriptEmbeddedPreviewUrl'
    | 'hideHeaderFilesMoreButton'
    | 'hideHeaderViewModeSwitch'
    | 'host'
    | 'isProjectBootstrapPreviewActive'
    | 'isTranscriptPreviewStoppable'
    | 'isTranscriptPreviewUrlFieldActive'
    | 'isTranscriptPreviewWaiting'
    | 'lastSyncedPreviewUrl'
    | 'matchesActivePreviewSummary'
    | 'mountFreshTranscriptTerminalSlide'
    | 'mountTranscriptEmbeddedPreview'
    | 'mountTranscriptEmptyPreview'
    | 'mountTranscriptReviewWidget'
    | 'mountedPreviewUrl'
    | 'offscreenPreviewHostElement'
    | 'pathsEqual'
    | 'persistTranscriptTerminalWorkspace'
    | 'pickTranscriptPreviewApp'
    | 'previewLaunchGeneration'
    | 'previewRuntimeByConversationId'
    | 'previewRuntimeFor'
    | 'previewScopeId'
    | 'previewUrlMatchesProject'
    | 'probeReadyPreviewUrl'
    | 'reconcileSupersededProjectPreviewUrl'
    | 'recoverTranscriptPreviewUrl'
    | 'refreshTranscriptPreviewProject'
    | 'refreshTranscriptPreviewTabProbe'
    | 'renderPreviewTab'
    | 'renderTranscriptTerminalDots'
    | 'renderTranscriptTerminalSlides'
    | 'requestTranscriptPreview'
    | 'resolvePreviewAnnotationScope'
    | 'resolveProjectScopedWorkspaceKey'
    | 'resolveRunnableTranscriptProjectRoot'
    | 'resolveTranscriptPreviewIdentity'
    | 'resolveTranscriptPreviewUrl'
    | 'resolveTranscriptProjectCwd'
    | 'resolveTranscriptTerminalTabTitle'
    | 'resolveTranscriptWorkspaceKey'
    | 'restoreTranscriptTerminalSlides'
    | 'scheduleTranscriptPreviewIdentityWatch'
    | 'scheduleTranscriptPreviewTabProbe'
    | 'setLastSyncedPreviewUrl'
    | 'setMountedPreviewUrl'
    | 'setProbeReadyPreviewUrl'
    | 'shouldKeepTranscriptPreviewTabProbe'
    | 'showTranscriptTerminalError'
    | 'stageTranscriptPreviewReadyUrl'
    | 'stopTranscriptPreview'
    | 'stopTranscriptPreviewIdentityWatch'
    | 'stopTranscriptPreviewTabProbe'
    | 'submitTranscriptReviewFeedback'
    | 'suspendTranscriptPreviewIframe'
    | 'switchTranscriptPreviewApp'
    | 'syncHeaderFilesMoreButton'
    | 'syncHeaderPreviewAppSwitchButton'
    | 'syncHeaderPreviewRunButton'
    | 'syncHeaderViewModeSwitch'
    | 'syncTranscriptTerminalResizeObserver'
    | 'toPersistedTerminalWorkspace'
    | 'transcriptHistoryUi'
    | 'transcriptPreviewAppPicker'
    | 'transcriptPreviewAppPickerCancel'
    | 'transcriptPreviewConversationScopeId'
    | 'transcriptPreviewEnsureRequests'
    | 'transcriptPreviewIdentityWatchTimer'
    | 'transcriptPreviewIdleDiscovery'
    | 'transcriptPreviewProbeIdleTicks'
    | 'transcriptPreviewProbeScopeKey'
    | 'transcriptPreviewProbeTimer'
    | 'transcriptPreviewProjectId'
    | 'tryMountProjectScopedPreview'
    | 'tryMountVerifiedTranscriptPreview'
    | 'updateTranscriptPreviewReadyOverlay'
    | 'updateTranscriptPreviewRunButtonState'
    | 'verifyMountedTranscriptPreviewIdentity'
    | 'wireTranscriptPreviewAnnotationScope';

/**
 * Members of {@link MobileProjectsTranscriptSurfacesUi} that the extracted helper functions access
 * through their `ctx` parameter.
 */
export interface MobileProjectsTranscriptSurfacesUiContext
    extends Pick<MobileProjectsTranscriptSurfacesUi, MobileProjectsTranscriptSurfacesUiContextMember> { }
