// *****************************************************************************
// Copyright (C) 2026 Theia contributors and Qaap product fork.
// SPDX-License-Identifier: EPL-2.0 OR GPL-2.0-only WITH Classpath-exception-2.0
// *****************************************************************************

// The shared contract between `MobileProjectsPanel` and the extracted free functions in the
// `mobile-projects-panel-{activity,init,render,streaming,timeline}.ts` cluster. Each extracted
// function receives the panel typed as `MobileProjectsPanelContext` instead of `any`.
//
// Unlike the smaller node-side contexts, the panel exposes ~180 members to its modules, so the
// contract is derived from the class with `Pick` instead of restating every signature: the member
// list below is the seam, and each member keeps the exact type the panel declares. Members named
// here are `public` + `@internal` on the panel. `import type` keeps this free of a runtime
// import cycle (the panel imports every extracted module).

import type { MobileProjectsPanel } from './mobile-projects-panel';

/** Panel members referenced by the extracted `mobile-projects-panel-*` modules. */
export type MobileProjectsPanelContextMember =
    | 'accountBtn'
    | 'activateMessagesSurfaceForExternalSubmit'
    | 'activeTasks'
    | 'agentFinishedToast'
    | 'agentsHubEmptySurfaceGuardDispose'
    | 'agentsHubInlineActive'
    | 'agentsHubInlineUi'
    | 'agentsHubLegacyInbox'
    | 'agentsHubSelectedProjectId'
    | 'agentsHubShellActive'
    | 'agUiFrontendTools'
    | 'appendHeaderOverflowSeparator'
    | 'applyComposerAttachmentsToDraft'
    | 'attachExternalComposerContext'
    | 'attachExternalFeedbackImageEntries'
    | 'backgroundContext'
    | 'backgroundTaskUi'
    | 'chatAgentService'
    | 'chatService'
    | 'closeHeaderIdeViewPickerMenu'
    | 'closeHeaderOverflowMenu'
    | 'commands'
    | 'commitMessageAi'
    | 'composerEditorContextService'
    | 'composerHeaderUi'
    | 'composerPromptImprover'
    | 'conversationActionsUi'
    | 'conversationFlags'
    | 'conversationOpenUi'
    | 'conversations'
    | 'copyActiveConversationToClipboard'
    | 'createChatInputWidget'
    | 'createChatViewWidget'
    | 'createDiffReviewWidget'
    | 'createHeaderIdeViewIcon'
    | 'createTranscriptFilesViewServices'
    | 'createTranscriptTerminalViewServices'
    | 'currentProjectsScrollHost'
    | 'dropComposerFiles'
    | 'ensureAgentsHubExecutionShellRendered'
    | 'ensureExternalSubmitConversationRendered'
    | 'ensureHeaderIdeViewPickerMenu'
    | 'ensureHeaderOverflowMenu'
    | 'ensureOverlayUi'
    | 'executionSurfaceTabsUi'
    | 'expandComposerDraftForSubmit'
    | 'expandedId'
    | 'formatContextChip'
    | 'getComposerSkills'
    | 'getComposerSlashCommands'
    | 'getComposerVariables'
    | 'getRegisteredLanguageModels'
    | 'handleComposerContextItemRemoved'
    | 'headerIdeViewPickerBtn'
    | 'headerIdeViewPickerDismiss'
    | 'headerIdeViewPickerHost'
    | 'headerIdeViewPickerMenu'
    | 'headerOverflowMenu'
    | 'headerOverflowMenuBtn'
    | 'headerOverflowMenuDismiss'
    | 'headerOverflowMenuGroups'
    | 'hide'
    | 'homeMode'
    | 'hubHeaderUi'
    | 'hubIncrementalUi'
    | 'hubLandingUi'
    | 'hubListRenderScheduler'
    | 'hubQueryUi'
    | 'hubView'
    | 'inboxPrUi'
    | 'inboxStream'
    | 'isAgentsHubExecutionSurfaceReady'
    | 'isCopyConversationEnabled'
    | 'isHeaderNewChatVisible'
    | 'isHeaderOverflowMenuItemEnabled'
    | 'isHeaderOverflowMenuItemVisible'
    | 'isPullRequestsSidebarVisible'
    | 'messageService'
    | 'missionControlHubUi'
    | 'mobileIdeViewPicker'
    | 'navigateHubTab'
    | 'notifyAgentUsesSettingsApiKey'
    | 'notifyWorkspaceHubBottomBarRefresh'
    | 'onBootstrapPreviewOpened'
    | 'onCancelConversation'
    | 'onNavigateToConversation'
    | 'onRetryConversation'
    | 'openAgentsHubInlineTranscript'
    | 'openAiConfigurationSheet'
    | 'openBillingSheet'
    | 'openConversationSummary'
    | 'openHeaderIdeViewPickerMenu'
    | 'openHeaderNewChat'
    | 'openHeaderOverflowMenu'
    | 'openInlineTranscript'
    | 'openPreferencesSheet'
    | 'openTranscriptChanges'
    | 'openTranscriptFile'
    | 'openTranscriptReviewFile'
    | 'openWorkHubSessionsSidebar'
    | 'overlayFactoryUi'
    | 'panelChromeUi'
    | 'panelLifecycleUi'
    | 'pickContextVariable'
    | 'positionHeaderIdeViewPickerMenu'
    | 'positionHeaderOverflowMenu'
    | 'preferenceService'
    | 'preparedCwdByProjectId'
    | 'previewClipboard'
    | 'previewInspectorDeps'
    | 'previewSurfaceRegistry'
    | 'projectBootstrap'
    | 'projectNavigationUi'
    | 'projectOwnsActiveBootstrap'
    | 'projects'
    | 'projectsService'
    | 'pullRequestDetail'
    | 'quickInputService'
    | 'readPreference'
    | 'refreshInboxPullRequests'
    | 'refreshProjects'
    | 'refreshProjectsInFlight'
    | 'removeExternalPreviewFeedbackChip'
    | 'render'
    | 'renderAgentsHubExecutionShell'
    | 'renderAgentsHubIdleSubmitOptimistic'
    | 'renderHeader'
    | 'renderHeaderOverflowMenuItems'
    | 'renderIdleSubmitOptimistic'
    | 'renderList'
    | 'renderSubtitle'
    | 'resetInboxPullRequestState'
    | 'resolveActiveComposerContextTarget'
    | 'resolveActiveConversationForCopy'
    | 'resolveActiveTranscriptChatHost'
    | 'resolveAgentsHubShellProject'
    | 'resolveAgentsHubShellSummary'
    | 'resolveAttachmentPreview'
    | 'resolveExternalComposerProject'
    | 'resolveExternalComposerUploadDir'
    | 'resolveShellSummary'
    | 'resolveVerifyChecks'
    | 'root'
    | 'scroll'
    | 'selectHubLandingView'
    | 'selectTranscriptTab'
    | 'sessionsSidebar'
    | 'sessionsSidebarContainer'
    | 'sessionsSidebarUi'
    | 'setMissionControlExpanded'
    | 'shouldEmbedSessionsSidebarInPanel'
    | 'shouldUseAgentsHubLanding'
    | 'soloExpanded'
    | 'stickyComposerAgentsUi'
    | 'stickyComposerContext'
    | 'stickyComposerRenderUi'
    | 'stickyComposerSheetsUi'
    | 'stickyComposerWorkspaceUi'
    | 'submitBackgroundAgentTask'
    | 'submitTranscriptViaBackendConversation'
    | 'subtitleUi'
    | 'syncCurrentProjectsScrollHost'
    | 'syncHeaderIdeViewPicker'
    | 'syncLandingHubListChrome'
    | 'tasksHubAttentionUi'
    | 'tasksHubUi'
    | 'teardownAgentsHubExecutionShell'
    | 'theiaChatSessionUi'
    | 'transcriptComposerUi'
    | 'transcriptController'
    | 'transcriptConversationCache'
    | 'transcriptLiveUi'
    | 'transcriptMessagesUi'
    | 'transcriptSheetUi'
    | 'transcriptStickyComposerUi'
    | 'transcriptSubmitUi'
    | 'transcriptSurfacesUi'
    | 'transcriptVerifyUi'
    | 'uploadComposerFeedbackImages'
    | 'visible'
    | 'whenFrontendReadyProvider'
    | 'workHubInboxUi'
    | 'workHubProjectSkillRoots';

/**
 * Panel fields that are `readonly` on the class but assigned once during construction by the
 * extracted `mobile-projects-panel-init` helpers (`applyPanelOptions`, `wireTranscriptFileOpeners`,
 * `createPanelRoot`). The context exposes them as writable so that constructor-time wiring
 * type-checks; the class itself keeps them `readonly`.
 */
export type MobileProjectsPanelInitAssignedMember =
    | 'activeTasks'
    | 'agentFinishedToast'
    | 'agUiFrontendTools'
    | 'applyComposerAttachmentsToDraft'
    | 'backgroundContext'
    | 'chatAgentService'
    | 'chatService'
    | 'commitMessageAi'
    | 'composerEditorContextService'
    | 'composerPromptImprover'
    | 'conversationFlags'
    | 'conversations'
    | 'createChatInputWidget'
    | 'createChatViewWidget'
    | 'createDiffReviewWidget'
    | 'createTranscriptFilesViewServices'
    | 'createTranscriptTerminalViewServices'
    | 'dropComposerFiles'
    | 'expandComposerDraftForSubmit'
    | 'formatContextChip'
    | 'getComposerSkills'
    | 'getComposerSlashCommands'
    | 'getComposerVariables'
    | 'getRegisteredLanguageModels'
    | 'headerOverflowMenuGroups'
    | 'homeMode'
    | 'inboxStream'
    | 'messageService'
    | 'mobileIdeViewPicker'
    | 'openAiConfigurationSheet'
    | 'openBillingSheet'
    | 'openPreferencesSheet'
    | 'openTranscriptFile'
    | 'openTranscriptReviewFile'
    | 'pickContextVariable'
    | 'preferenceService'
    | 'previewClipboard'
    | 'previewInspectorDeps'
    | 'previewSurfaceRegistry'
    | 'projectBootstrap'
    | 'quickInputService'
    | 'readPreference'
    | 'resolveAttachmentPreview'
    | 'resolveVerifyChecks'
    | 'root'
    | 'sessionsSidebarContainer'
    | 'uploadComposerFeedbackImages'
    | 'whenFrontendReadyProvider'
    | 'workHubProjectSkillRoots';

type MobileProjectsPanelWritable<T> = { -readonly [K in keyof T]: T[K] };

/**
 * Members of {@link MobileProjectsPanel} that the extracted helper functions access through their
 * `ctx` / `self` parameter.
 */
export interface MobileProjectsPanelContext extends
    Pick<MobileProjectsPanel, Exclude<MobileProjectsPanelContextMember, MobileProjectsPanelInitAssignedMember>>,
    MobileProjectsPanelWritable<Pick<MobileProjectsPanel, MobileProjectsPanelInitAssignedMember>> { }
